added UI script and made everything more generic

diff --git a/init/init b/init/init
--- a/init/init
+++ b/init/init
@@ -8,37 +8,181 @@ then
   WD="$1"
 fi
 
-ENABLED_DIR=$WD/enabled # directory for enabled services
-HOLD=hold # file for temporarily disabling a service
-LAST_ENABLED= # list of services ("name:PID")
-LOG=log # cumulative log file
-POST_BOOT_D=$WD/post-boot.d # post-boot scripts directory
-PRE_HALT_D=$WD/pre-halt.d # pre-halt scripts directory
-RUN=run # entry point for a service
+SHELL=`cat "$WD/shell" 2>&1`
 
-# extract the name from a service
-_get_service_name() {
-  echo "$1" | cut -d ':' -f 1
+if [ $? != "0" ]
+then
+  # use default value
+  
+  SHELL=sh
+fi
+SIG=`cat "$WD/sig" 2>&1`
+
+if [ $? != "0" ]
+then
+  # use default value
+  
+  SIG=TERM
+fi
+SLEEP=`cat "$WD/sleep" 2>&1`
+
+if [ $? != "0" ]
+then
+  # use default value
+  
+  SLEEP=1
+fi
+
+# nonconfigurable globals
+
+ALIVE=1 # global halt trigger
+ENABLED_DIR=$WD/enabled # directory for enabled services
+HOLD_FILE=hold # hold file for a service (its presence disables the service)
+LAST_ENABLED= # list of services
+LOG_FILE=$WD/log # global log file
+OUT_FILE=out # service output
+PID_FILE=pid # PID file
+POST_BOOT_D_DIR=$WD/post-boot.d # post-boot scripts directory
+PRE_HALT_D_DIR=$WD/pre-halt.d # pre-halt scripts directory
+RUN_FILE=run # service entry point
+
+# enable a service and return its PID, or 0 on failure
+enable_service() {
+  SERVICE_DIR="$ENABLED_DIR/$1"
+  SERVICE_RUN_FILE="$SERVICE_DIR/$RUN_FILE"
+  
+  # check for a hold on the service
+  
+  if [ -e "$SERVICE_DIR/$HOLD_FILE" ]
+  then
+    # there's a hold on the service
+
+    return 0
+  fi
+  
+  # check for an entry point
+  
+  if [ ! -e "$SERVICE_RUN_FILE" ]
+  then
+    # no service entry point
+    
+    return 0
+  fi
+  
+  # check whether the service is already running
+  
+  if is_running "$1"
+  then
+    # already running
+    
+    get_service_pid "$1"
+    return $?
+  fi
+  
+  # not running
+  
+  "$SHELL" "$SERVICE_RUN_FILE" > "$SERVICE_DIR/$OUT_FILE" 2>&1 &
+  PID=$!
+  
+  if [ $PID != "0" ]
+  then
+    set_service_pid "$1" $PID
+    
+    if [ -z `echo "$LAST_ENABLED" | grep "^$1\$"` ]
+    then
+      log "$1" "Started service at PID $PID."
+    else
+      log "$1" "Restarted service at PID $PID."
+    fi
+  else
+    log "$1" "Failed to start service."
+  fi
+  return $PID
 }
 
-# extract the PID from a service
-_get_service_pid() {
-  echo "$1" | cut -d ':' -f 2
+# get a service's PID
+get_service_pid() {
+  PID=`cat "$ENABLED_DIR/$1/$PID_FILE" 2>&1`
+  
+  if [ $? != "0" ]
+  then
+    # no PID file
+    return 0
+  fi
+  return $PID > /dev/null 2>&1
+  return 0 # invalid PID
+}
+
+# check whether a service is running
+is_running() {
+  get_service_pid "$1"
+  PID=$?
+  
+  if [ $PID = "0" ]
+  then
+    return 1
+  fi
+  
+  if [ ! -z `pgrep -f "$ENABLED_DIR/$1/$RUN_FILE" | grep "^$PID\$"` ]
+  then
+    return 0
+  fi
+  return 1
 }
 
 # kill a service
 kill_service() {
-  kill -s TERM `_get_service_pid "$1"`
+  # check whether it's running
+   
+  if ! is_running "$1"
+  then
+    return 0
+  fi
+  
+  # get the PID
+  
+  get_service_pid "$1"
+  PID=$?
+  
+  if [ $PID = "0" ]
+  then
+    return 0
+  fi
+  
+  # kill it
+  
+  kill -s "$SIG" "$PID"
+  RETVAL=$?
+  
+  if [ $RETVAL = "0" ]
+  then
+    # remove the PID file
+    
+    unset_service_pid "$1"
+    log "$1" "Stopped service with SIG$SIG."
+  else
+    log "$1" "Failed to stop service with SIG$SIG."
+  fi
+  return $RETVAL
 }
 
-# log service information to the service's log file and STDOUT
+# log service information to the global log file and STDOUT
+# of the format "DATE [CLASS_SPEC] MESSAGE"
 log() {
-  echo "$2" | tee -a "$ENABLED_DIR/"`_get_service_name "$1"`"/$LOG"
+  CLASS_SPEC="Service \"$1\""
+  
+  if [ -z "$1" ]
+  then
+    # global message
+    
+    CLASS_SPEC=System
+  fi
+  echo `date` "[$CLASS_SPEC]" "$2" | tee -a "$LOG_FILE"
 }
 
 # maintain enabled services
 maintain_services() {
-  while [ 1 ]
+  while [ $ALIVE ]
   do
     # redetermine service list,
     # and disable those no longer listed
@@ -46,63 +190,43 @@ maintain_services() {
     NEXT_ENABLED=
     TO_DISABLE="$LAST_ENABLED"
 
-    for NAME in $(ls "$ENABLED_DIR")
+    for SERVICE in $(ls "$ENABLED_DIR")
     do
-      # omit the service from the kill list
+      # determine whether to disable the service
       
       _TO_DISABLE=
-       
+      
       for ENABLED in $TO_DISABLE
       do
-        if [ -z `echo "$ENABLED" | grep "^$NAME:"` ] || [ -e "$ENABLED_DIR/"`_get_service_name "$ENABLED"`"/$HOLD" ]
+        # only skip if it's the current service,
+        # and there's no hold file
+        
+        if [ "$ENABLED" = "$SERVICE" ] && [ ! -e "$ENABLED_DIR/$ENABLED/$HOLD_FILE" ]
         then
-          _TO_DISABLE="$_TO_DISABLE `echo \"$ENABLED\"`" # workaround to preserve quotation when necessary
-	fi
+          # don't disable
+          
+          continue
+        fi
+        _TO_DISABLE="$_TO_DISABLE\n"`echo "$ENABLED"`
       done
-      TO_DISABLE="$_TO_DISABLE"
+      TO_DISABLE=`strip_preceding_line "$_TO_DISABLE"`
       
-      if [ -e "$ENABLED_DIR/$NAME/$HOLD" ]
+      # don't start any new services
+
+      if [ ! $ALIVE ]
       then
-	# don't even bother starting it
-
-        continue
+        return
       fi
-      
-      # determine whether the service is already running
-      
-      LAST_PID=
-      SCRIPT="$ENABLED_DIR/$NAME/$RUN"
-      PID=`pgrep -f "$SCRIPT"`
 
-      for ENABLED in $(echo "$LAST_ENABLED")
-      do
-        if [ ! -z `echo "$ENABLED" | grep "^$NAME:"` ]
-        then
-          LAST_PID=`_get_service_pid "$ENABLED"`
-          break
-	fi
-      done
+      # attempt to enable the service
       
-      # ensure the service is running
-
-      if [ -z "$LAST_PID" ] || [ -z `pgrep -f "$SCRIPT" | grep "^$LAST_PID\$"` ]
+      enable_service "$SERVICE"
+      PID=$?
+      
+      if [ "$PID" != "0" ]
       then
-	# service dead or not started
-	
-	[ -e "$SCRIPT" ] && sh "$SCRIPT" & #> /dev/null 2>&1 &
-	PID=$!
-        SERVICE=`_make_service "$NAME" "$PID"`
-
-	if [ -z "$LAST_PID" ]
-        then
-	  log "$SERVICE" "Started service \"$NAME\" at PID $PID."
-	else
-	  log "$SERVICE" "Restarted service \"$NAME\" at PID $PID."
-	fi
-      else
-        SERVICE=`_make_service "$NAME" "$LAST_PID"`
+        NEXT_ENABLED="$NEXT_ENABLED\n"`echo "$SERVICE"`
       fi
-      NEXT_ENABLED="$NEXTENABLED `_make_service \"$NAME\" \"$PID\"`"
     done
     
     # disable services
@@ -110,45 +234,104 @@ maintain_services() {
     for ENABLED in $TO_DISABLE
     do
       kill_service "$ENABLED"
-      log "$ENABLED" "Stopped service "`_get_service_name "$ENABLED"`" at PID "`_get_service_pid "$ENABLED"`"."
     done
-    LAST_ENABLED="$NEXT_ENABLED"
-    sleep 1
+    LAST_ENABLED=`strip_preceding_line "$NEXT_ENABLED"`
+    sleep "$SLEEP"
   done
-}
-
-# construct a service from a name and PID
-_make_service() {
-  echo "$1:$2"
 }
 
 # boot the init system
 on_boot() {
-  run_scripts_in_order "$POST_BOOT_D"
+  log "" "Entering post-boot phase."
+  run_scripts_in_order "$POST_BOOT_D_DIR"
 }
 
 # halt the init system
 on_halt() {
+  ALIVE=0 # global halt order
+  
+  log "" "Received terminating signal."
+  log "" "Entering pre-halt phase."
+
+  sleep "$SLEEP" # wait for the maintenance function to terminate
+
   for ENABLED in $LAST_ENABLED
   do
     kill_service "$ENABLED"
-    log "$ENABLED" "Stopped service "`_get_service_name "$ENABLED"`" at PID "`_get_service_pid "$ENABLED"`"."
   done
-  run_scripts_in_order "$PRE_HALT_D"
-  exit
+  run_scripts_in_order "$PRE_HALT_D_DIR"
+  exit 0
 }
 
 # run scripts within a directory in sorted (using `sort -h`) order
 run_scripts_in_order() {
+  if [ ! -d "$1" ]
+  then
+    log "" "Invalid script directory."
+    return 1
+  fi
+  
   for SCRIPT in $(ls "$1" | sort -h)
   do
-    sh "$1/$SCRIPT"
+    SCRIPT="$1/$SCRIPT"
+    log "" "Executing \"$SCRIPT\"..."
+    sh "$SCRIPT"
   done
+  log "" "Done executing scripts."
+}
+
+# set a service's PID
+set_service_pid() {
+  if [ -z "$1" ]
+  then
+    return 1
+  fi
+  echo "$2" > "$ENABLED_DIR/$1/$PID_FILE"
+  return $?
+}
+
+# strip the preceding line from a string
+strip_preceding_line() {
+  echo "$1" | cut --complement -d "
+" -f 1
+}
+
+# unset a service's PID
+unset_service_pid() {
+  if [ -z "$1" ]
+  then
+    return 1
+  fi
+  rm "$ENABLED_DIR/$1/$PID_FILE" > /dev/null 2>&1
 }
 
 # prep eventual halt
 
 trap on_halt ABRT HUP INT TERM
+
+# create directories
+
+for DIR in "$WD" "$ENABLED_DIR" "$POST_BOOT_D_DIR" "$PRE_HALT_D_DIR"
+do
+  if [ ! -e "$DIR" ]
+  then
+    if ! mkdir -p "$DIR"
+    then
+      log "" "Failed to create \"$DIR\"." > /dev/null 2>&1
+      echo "Failed to create \"$DIR\"."
+      exit 1
+    fi
+  elif [ ! -d "$DIR" ]
+  then
+    log "" "\"$DIR\" exists, and isn't a directory." > /dev/null 2>&1
+    echo "\"$DIR\" exists, and isn't a directory."
+    exit 1
+  fi
+done
+
+# clear global log
+
+> "$LOG_FILE"
 
 # 3-stage system
 
